from pathlib import Path
import argparse
import hashlib
import json

from capstone import Cs, CS_ARCH_ARM, CS_MODE_THUMB, CS_MODE_LITTLE_ENDIAN
from capstone.arm import ARM_OP_IMM

ROOT = Path(__file__).resolve().parent
ap = argparse.ArgumentParser(description="Validate the generated CFS RFID diagnostics patch")
ap.add_argument("--input", required=True, help="original stock CFS image")
ap.add_argument("--patched", required=True, help="patched CFS image")
ap.add_argument("--manifest", required=True, help="manifest generated by build_patch.py")
ap.add_argument("--report", default=str(ROOT / "validation_report.json"))
args = ap.parse_args()
manifest = json.loads(Path(args.manifest).read_text())
source = Path(args.input).read_bytes()
patched = Path(args.patched).read_bytes()

APP_BASE = int(manifest["layout"]["application_base"], 16)
HOOK_OFFSET = int(manifest["layout"]["hook_offset"], 16)
HANDLER_OFFSET = int(manifest["layout"]["handler_offset"], 16)
HANDLER_ADDR = int(manifest["layout"]["handler_runtime_address"], 16)
HANDLER_SIZE = manifest["layout"]["handler_size"]

ALLOWED_CALLS = {
    0x08017828: "rfid_hw_init",
    0x08017DA0: "reader_cleanup",
    0x0801802C: "card_detect_select",
    0x08018066: "card_auth_key_a",
    0x0801831A: "card_read_16",
    0x08019BD6: "rs485_response",
}
FORBIDDEN_WRITE = 0x08018D6A

def sha(data):
    return hashlib.sha256(data).hexdigest()

errors = []
if sha(source) != manifest["source"]["sha256"]:
    errors.append("source SHA mismatch")
if sha(patched) != manifest["output"]["sha256"]:
    errors.append("patched SHA mismatch")
if len(patched) != manifest["output"]["size"]:
    errors.append("patched size mismatch")

# Existing application must differ only at the 4-byte dispatcher hook.
diff = [i for i,(a,b) in enumerate(zip(source, patched[:len(source)])) if a != b]
if diff != list(range(HOOK_OFFSET, HOOK_OFFSET + 4)):
    errors.append(f"unexpected changes inside original image: {diff[:40]}")

if patched[:HOOK_OFFSET] != source[:HOOK_OFFSET]:
    errors.append("prefix before hook changed")
if patched[HOOK_OFFSET + 4:len(source)] != source[HOOK_OFFSET + 4:]:
    errors.append("stock image after hook changed")

md = Cs(CS_ARCH_ARM, CS_MODE_THUMB | CS_MODE_LITTLE_ENDIAN)
md.detail = True

hook_insns = list(md.disasm(patched[HOOK_OFFSET:HOOK_OFFSET+4], APP_BASE + HOOK_OFFSET))
if len(hook_insns) != 1 or hook_insns[0].mnemonic != "b.w":
    errors.append("hook is not one B.W instruction")
else:
    target = hook_insns[0].operands[0].imm
    if target != HANDLER_ADDR:
        errors.append(f"hook target {target:#x} != handler {HANDLER_ADDR:#x}")

handler = patched[HANDLER_OFFSET:HANDLER_OFFSET + HANDLER_SIZE]
insns = list(md.disasm(handler, HANDLER_ADDR))
covered = sum(i.size for i in insns)
if covered != HANDLER_SIZE:
    errors.append(f"handler disassembly covers {covered}/{HANDLER_SIZE} bytes")

calls = []
for insn in insns:
    if insn.mnemonic in ("bl", "blx") and insn.operands and insn.operands[0].type == ARM_OP_IMM:
        target = insn.operands[0].imm
        calls.append(target)
        if target == FORBIDDEN_WRITE:
            errors.append("handler references RFID write routine")
        if target not in ALLOWED_CALLS:
            errors.append(f"unexpected external call {target:#x}")

for target in ALLOWED_CALLS:
    if target not in calls:
        errors.append(f"expected helper not referenced: {target:#x}")

# Verify stock fallback branch and literal restoration are visible.
text = "\n".join(f"{i.mnemonic} {i.op_str}" for i in insns)
for required in (
    "cmp r0, #0x57",
    "cmp r0, #0xe",
    "b.w #0x801a3e0",
    "b.w #0x801a2e8",
    "bic r1, r7, #3",
    "pop {r3, r4, r5, r6, r7, pc}",
):
    if required not in text:
        errors.append("missing expected instruction: " + required)

# The patched 1.1.3 image remains far below the known stock 1.5.0 image size.
if len(patched) >= manifest["layout"]["known_larger_stock_image_size"]:
    errors.append("patched image not below known later stock image size")

result = {
    "ok": not errors,
    "errors": errors,
    "source_sha256": sha(source),
    "patched_sha256": sha(patched),
    "changed_original_offsets": [hex(i) for i in diff],
    "hook": [
        {
            "address": f"0x{i.address:08x}",
            "bytes": i.bytes.hex(),
            "mnemonic": i.mnemonic,
            "operands": i.op_str,
        }
        for i in hook_insns
    ],
    "handler_bytes": HANDLER_SIZE,
    "external_calls": [
        {"address": f"0x{x:08x}", "name": ALLOWED_CALLS.get(x, "unexpected")}
        for x in calls
    ],
    "forbidden_write_reference": FORBIDDEN_WRITE in calls,
}
Path(args.report).write_text(json.dumps(result, indent=2) + "\n")
print(json.dumps(result, indent=2))
if errors:
    raise SystemExit(1)